### ISSUE TITLE
Test that annotated images include alt text

### ISSUE THREAD

**Issue by kimisgold** [omeka-s-modules/ImageAnnotate#7]
The `render-alt-text` branch updates the public annotated image markup to include alt text if the media or asset has it set. If there is no available alt text, the alt attribute is empty. Test both annotated media and assets that have alt text, as well as some without.

**Comment by aviannamiller** [comment]
This generally works as expected for both annotated media and assets, with or without alt text, except when dealing with media added from private items, viewed as a logged out user. In that case, the image of course does not display, but the following error message displays whether alt text has been set or not:
```
Notice: Undefined variable: imageAlt in /var/www/html/amiller/OmekaS/modules/ImageAnnotate/src/Site/BlockLayout/ImageAnnotateMedia.php on line 123
```

**Comment by kimisgold** [comment]
This seems to be because the block markup was still being rendered without any public media available. That should be fixed now.

**Comment by aviannamiller** [comment]
There doesn't seem to be a change. I should also note that if a block is rendered for an image annotate asset or media but no image is attached, the same error displays, even for logged in users:

```
Notice: Undefined variable: imageAlt in /var/www/html/amiller/OmekaS/modules/ImageAnnotate/src/Site/BlockLayout/ImageAnnotateAsset.php on line 87

Notice: Undefined variable: imageAlt in /var/www/html/amiller/OmekaS/modules/ImageAnnotate/src/Site/BlockLayout/ImageAnnotateMedia.php on line 123
```

**Comment by kimisgold** [comment]
I don't know how I missed the alert again before, but I think it's fixed now.

**Comment by aviannamiller** [comment]
That did it for annotated images added as media, but assets still have the same error.

**Comment by kimisgold** [comment]
Asset should have the same treatment now.

**Comment by aviannamiller** [comment]
Thank you! That's fixed. This looks to be all set to close.
